name: dev
root: ~/Documents/01_PROJECTS/
windows:
  - legendis-website:
      root: ~/Documents/01_PROJECTS/Legendis/dev/legendis-next-app/
      layout: main-vertical
      synchronize: after
      panes:
        - l .
  - prod203-website :
      root: ~/Projects/pro/prod203-legendis/dev/prod203-next-app/
      layout: main-vertical
      synchronize: after
      panes:
        - l .
  - prod203-admin :
      root: ~/Projects/pro/prod203-legendis/dev/prod203-admin/
      layout: main-vertical
      synchronize: after
      panes:
        - l .
  - sestini-pizza-website :
      root: ~/Projects/pro/sestini-pizza-2023/
      layout: main-vertical
      synchronize: after
      panes:
        - l .
  - sestini-pizza-admin :
      root: ~/Projects/pro/sestini-pizza-2023-admin/
      layout: main-vertical
      synchronize: after
      panes:
        - l .
  - digitalsolutionstudio :
      root: ~/Documents/01_PROJECTS/dev_digital-solution-studio/digital-solution.studio/
      layout: main-vertical
      synchronize: after
      panes:
        - l .
